#!/bin/bash
echo "--------------------------"
echo " Argon Configuration Tool "
echo "--------------------------"
get_number () {
	read curnumber
	if [ -z "$curnumber" ]
	then
		echo "-2"
		return
	elif [[ $curnumber =~ ^[+-]?[0-9]+$ ]]
	then
		if [ $curnumber -lt 0 ]
		then
			echo "-1"
			return
		elif [ $curnumber -gt 100 ]
		then
			echo "-1"
			return
		fi	
		echo $curnumber
		return
	fi
	echo "-1"
	return
}

mainloopflag=1
while [ $mainloopflag -eq 1 ]
do
	echo
	echo "Choose Option:"
	echo "  1. Configure Fan"
	echo "  2. Configure IR"
	echo "  3. Configure RTC and/or Schedule"
	echo "  4. Configure OLED"
	echo "  5. Uninstall"
	echo ""
	echo "  0. Exit"
	echo -n "Enter Number (0-5):"
	newmode=$( get_number )
	if [ $newmode -eq 0 ]
	then
		echo "Thank you."
		mainloopflag=0
	elif [ $newmode -eq 1 ]
	then
		/etc/argon/argonone-fanconfig.sh
		mainloopflag=0
	elif [ $newmode -eq 2 ]
	then
		/etc/argon/argonone-ir
		mainloopflag=0
	elif [ $newmode -eq 3 ]
	then
		/etc/argon/argoneon-rtcconfig.sh
		mainloopflag=0
	elif [ $newmode -eq 4 ]
	then
		/etc/argon/argoneon-oledconfig.sh
		mainloopflag=0
	elif [ $newmode -eq 5 ]
	then
		/etc/argon/argon-uninstall.sh
		mainloopflag=0
	fi
done
