#!/bin/bash

get_temp()
{
    device=`echo $1 | awk -F':' '{print $2}'`
    smartctl -d sat -A ${device} | grep 194 | awk -F" " '{print $10}'
}

#
#
#
while getopts ":n:" option ; do
    case $option in
        n) # process argument
           get_temp $OPTARG
           exit;;
    esac
done
